### ISSUE TITLE
Cannot Fetch Token Prices

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/AutoTx#157] opened 2024-04-09 00:59 UTC
```
What do you want to do?: "what is the price of ETH?"
Network: MAINNET
Agent address: 0x3c41B85b7DA02De3739270BB1416b4b0dF61059b
Smart account connected: 0x69B5649342A4AE1DD973692c257479C97838bd41
Running AutoTx with the following prompt:  "what is the price of ETH?"
Unsupported prompt: The current agents and tools do not support retrieving the live price of ETH or any other cryptocurrency.
New prompt: What's the most valuable meme coin? 
Unsupported prompt: Determining the most valuable meme coin requires real-time market data analysis, which is outside the scope of the agents' capabilities.
New prompt: 
```

**Comment by nerfZael** [comment] 2024-04-09 12:42
I could not reproduce it. With verbose mode it always displays the price and without it nothing happens (which will be addressed in this issue: https://github.com/polywrap/AutoTx/issues/158)

We do include tool descriptions in build goal as seen here: https://github.com/polywrap/AutoTx/blob/5ef1d2455801b9ae5d04fbc70ef951dc6e2a20cd/autotx/AutoTx.py#L108

**Closed** 2024-04-09 20:59 UTC
Labels: pri: high
